Repository AY2223S2-CS2113-W12-2/tp, pull requests merged in 2023-03, with the labels that each got.

#13 Add CompanyList class
  src/main/java/CompanyList.java
Labels: type.Task

#14 UI
  src/main/java/seedu/duke/Ui.java
Labels: type.Story

#16 Add Eventus main class
  src/main/java/Eventus.java
Labels: type.Task

#22 Add wrong format exception and update list venue code
  src/main/java/Eventus.java
  src/main/java/seedu/duke/Command/Command.java
  src/main/java/seedu/duke/Command/ListVenueCommand.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/WrongFormatException.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/ListCompanyCommand.java
  src/main/java/seedu/duke/command/ListVenueCommand.java
  src/main/java/seedu/duke/venue/Venue.java
  src/main/java/seedu/duke/venue/VenueList.java
Labels: priority.High

#35 Event class
  src/main/java/seedu/duke/Eventus.java
  src/main/java/seedu/duke/command/ChooseVenueCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/company/CompanyList.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/VenueListStorage.java
  src/main/java/seedu/duke/venue/VenueList.java
Labels: priority.High

#59 Event details storage method, comments, developer guide
  data/eventDetails.txt
  docs/DeveloperGuide.md
  docs/UML/Image/broadOverview.png
  docs/UML/Style.puml
  docs/UML/broadOverview.puml
  src/main/java/seedu/duke/Eventus.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ChooseVenueCommand.java
  src/main/java/seedu/duke/command/ConfirmCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/FindCompanyCommand.java
  src/main/java/seedu/duke/command/FindIndustryCommand.java
  src/main/java/seedu/duke/command/ListCompanyCommand.java
  src/main/java/seedu/duke/command/ListUnconfirmedCommand.java
  src/main/java/seedu/duke/command/ListVenueCommand.java
  src/main/java/seedu/duke/command/LoadSampleCompanyCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/UnconfirmCommand.java
  src/main/java/seedu/duke/data/VenueListData.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/exception/EmptyListException.java
  src/main/java/seedu/duke/exception/InputMismatchException.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
  src/main/java/seedu/duke/exception/NoSavedInformationException.java
  src/main/java/seedu/duke/exception/WrongFormatException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/CompanyListDecoder.java
  src/main/java/seedu/duke/storage/EventDetailsStorage.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/VenueListStorage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/venue/VenueList.java
Labels: documentation, enhancement, type.Story
