Repository AY2223S2-CS2113-W12-2/tp, pull requests merged in 2023-04, with the labels that each got.

#125 PED_bug_fixes
  src/main/java/seedu/duke/Eventus.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ChooseVenueCommand.java
  src/main/java/seedu/duke/command/ConfirmCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/ListCompanyCommand.java
  src/main/java/seedu/duke/command/ListUnconfirmedCommand.java
  src/main/java/seedu/duke/command/ListVenueCommand.java
  src/main/java/seedu/duke/command/UnconfirmCommand.java
  src/main/java/seedu/duke/company/CompanyList.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/CompanyListDecoder.java
  src/main/java/seedu/duke/storage/CompanyListEncoder.java
  src/main/java/seedu/duke/storage/EventDetailsStorage.java
Labels: bug

#123 PPP draft
  docs/team/manoj364.md
Labels: documentation

#124 UG bug fixes
  docs/UserGuide.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation

#127 Create personal PPP and UML diagrams
  docs/UML/chooseVenueCommand.puml
  docs/UML/event.puml
  docs/team/wuzhzn.md
Labels: documentation

#128 Update PPP
  docs/team/kishore-a00.md
Labels: documentation

#122 Improve userguide
  docs/UserGuide.md
  src/main/java/seedu/duke/parser/Parser.java
Labels: documentation

#133 Documentation updates
  docs/UML/Image/Ui_class.png
  docs/UML/Ui_class.puml
  docs/UserGuide.md
  docs/team/manoj364.md
  src/main/java/seedu/duke/ui/Ui.java
Labels: documentation

#134 Fix Bug updates and update UG, DG and Readme
  docs/README.md
  docs/UML/Image/CommandClassDiagram.png
  docs/UserGuide.md
  src/main/java/seedu/duke/Eventus.java
  src/main/java/seedu/duke/command/FindIndustryCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/exception/EmptyFieldException.java
  src/main/java/seedu/duke/exception/EmptyListException.java
  src/main/java/seedu/duke/exception/RepeatedFieldsException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: bug, documentation

#136 Updates to PPP & DG
  docs/DeveloperGuide.md
  docs/UML/Duplication_checker.puml
  docs/UML/Image/Duplication_checker.png
  docs/UML/Image/Ui_class.png
  docs/UML/Ui_class.puml
  docs/team/manoj364.md
  src/test/java/seedu/duke/company/CompanyListTest.java
Labels: documentation

#147 UML update
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UML/Duplication_checker.puml
  docs/UML/Image/Duplication_checker.png
  docs/UML/Image/Ui_class.png
  docs/UML/Ui_class.puml
  docs/team/manoj364.md
  src/main/java/seedu/duke/company/CompanyList.java
Labels: documentation

#150 Add table of contents to Developer Guide and fix minor formatting issues
  docs/DeveloperGuide.md
Labels: documentation

#154 Update description of Filter venues feature in User Guide
  docs/UserGuide.md
Labels: documentation
